name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  

    - name: Build Nginx image
      run: |
        docker build -t my-nginx:latest -f Dockerfile.nginx .

    - name: Build PostgreSQL image
      run: |
        docker build -t my-postgres:latest -f Dockerfile.postgres .
